package cn.kgc.mapper;

import cn.kgc.entity.HotelOrder;
import cn.kgc.entity.HotelOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HotelOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    long countByExample(HotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int deleteByExample(HotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int insert(HotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int insertSelective(HotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    List<HotelOrder> selectByExample(HotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    HotelOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") HotelOrder record, @Param("example") HotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByExample(@Param("record") HotelOrder record, @Param("example") HotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByPrimaryKeySelective(HotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByPrimaryKey(HotelOrder record);
}