package cn.kgc.mapper;

import cn.kgc.entity.RestaurantOrder;
import cn.kgc.entity.RestaurantOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RestaurantOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    long countByExample(RestaurantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int deleteByExample(RestaurantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int insert(RestaurantOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int insertSelective(RestaurantOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    List<RestaurantOrder> selectByExample(RestaurantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    RestaurantOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") RestaurantOrder record, @Param("example") RestaurantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByExample(@Param("record") RestaurantOrder record, @Param("example") RestaurantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByPrimaryKeySelective(RestaurantOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantorder
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByPrimaryKey(RestaurantOrder record);
}