package cn.kgc.mapper;

import cn.kgc.entity.RoomType;
import cn.kgc.entity.RoomTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoomTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    long countByExample(RoomTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int deleteByExample(RoomTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int insert(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int insertSelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    List<RoomType> selectByExample(RoomTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    RoomType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") RoomType record, @Param("example") RoomTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByExample(@Param("record") RoomType record, @Param("example") RoomTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByPrimaryKeySelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByPrimaryKey(RoomType record);
}