package cn.kgc.mapper;

import cn.kgc.entity.TourOrder;
import cn.kgc.entity.TourOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TourOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourorder
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    long countByExample(TourOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourorder
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    int deleteByExample(TourOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourorder
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourorder
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    int insert(TourOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourorder
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    int insertSelective(TourOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourorder
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    List<TourOrder> selectByExample(TourOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourorder
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    TourOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourorder
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") TourOrder record, @Param("example") TourOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourorder
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    int updateByExample(@Param("record") TourOrder record, @Param("example") TourOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourorder
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    int updateByPrimaryKeySelective(TourOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourorder
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    int updateByPrimaryKey(TourOrder record);
}