package cn.kgc.mapper;

import cn.kgc.entity.Tour;
import cn.kgc.entity.TourExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface TourMapper {

    List<Tour> selectAll(RowBounds rowBounds);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    long countByExample(TourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int deleteByExample(TourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int insert(Tour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int insertSelective(Tour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    List<Tour> selectByExample(TourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    Tour selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") Tour record, @Param("example") TourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByExample(@Param("record") Tour record, @Param("example") TourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByPrimaryKeySelective(Tour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    int updateByPrimaryKey(Tour record);
}