package cn.kgc.entity;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.tid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.uName
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.date
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String picpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.tid
     *
     * @return the value of comment.tid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.tid
     *
     * @param tid the value for comment.tid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.uName
     *
     * @return the value of comment.uName
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.uName
     *
     * @param uname the value for comment.uName
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.date
     *
     * @return the value of comment.date
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.date
     *
     * @param date the value for comment.date
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.mark
     *
     * @return the value of comment.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.mark
     *
     * @param mark the value for comment.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.picPath
     *
     * @return the value of comment.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.picPath
     *
     * @param picpath the value for comment.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}