package cn.kgc.entity;

public class Hotel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.level
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.hotelDescribe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String hoteldescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.price
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Double mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String picpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.picPath2
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String picpath2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.city
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.id
     *
     * @return the value of hotel.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.id
     *
     * @param id the value for hotel.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.name
     *
     * @return the value of hotel.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.name
     *
     * @param name the value for hotel.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.level
     *
     * @return the value of hotel.level
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.level
     *
     * @param level the value for hotel.level
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.hotelDescribe
     *
     * @return the value of hotel.hotelDescribe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getHoteldescribe() {
        return hoteldescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.hotelDescribe
     *
     * @param hoteldescribe the value for hotel.hotelDescribe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setHoteldescribe(String hoteldescribe) {
        this.hoteldescribe = hoteldescribe == null ? null : hoteldescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.price
     *
     * @return the value of hotel.price
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.price
     *
     * @param price the value for hotel.price
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.mark
     *
     * @return the value of hotel.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Double getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.mark
     *
     * @param mark the value for hotel.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setMark(Double mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.picPath
     *
     * @return the value of hotel.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.picPath
     *
     * @param picpath the value for hotel.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.picPath2
     *
     * @return the value of hotel.picPath2
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getPicpath2() {
        return picpath2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.picPath2
     *
     * @param picpath2 the value for hotel.picPath2
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPicpath2(String picpath2) {
        this.picpath2 = picpath2 == null ? null : picpath2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.city
     *
     * @return the value of hotel.city
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.city
     *
     * @param city the value for hotel.city
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}