package cn.kgc.entity;

public class Journey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.tid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.times
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.content
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String picpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.id
     *
     * @return the value of journey.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.id
     *
     * @param id the value for journey.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.tid
     *
     * @return the value of journey.tid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.tid
     *
     * @param tid the value for journey.tid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.times
     *
     * @return the value of journey.times
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.times
     *
     * @param times the value for journey.times
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.name
     *
     * @return the value of journey.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.name
     *
     * @param name the value for journey.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.content
     *
     * @return the value of journey.content
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.content
     *
     * @param content the value for journey.content
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.picPath
     *
     * @return the value of journey.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.picPath
     *
     * @param picpath the value for journey.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }
}