package cn.kgc.entity;

public class Restaurant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.restaurantDescribe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String restaurantdescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.price
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Double mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String picpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.picPath2
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String picpath2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.reviews
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer reviews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.city
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.id
     *
     * @return the value of restaurant.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.id
     *
     * @param id the value for restaurant.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.name
     *
     * @return the value of restaurant.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.name
     *
     * @param name the value for restaurant.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.restaurantDescribe
     *
     * @return the value of restaurant.restaurantDescribe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getRestaurantdescribe() {
        return restaurantdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.restaurantDescribe
     *
     * @param restaurantdescribe the value for restaurant.restaurantDescribe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setRestaurantdescribe(String restaurantdescribe) {
        this.restaurantdescribe = restaurantdescribe == null ? null : restaurantdescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.price
     *
     * @return the value of restaurant.price
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.price
     *
     * @param price the value for restaurant.price
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.mark
     *
     * @return the value of restaurant.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Double getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.mark
     *
     * @param mark the value for restaurant.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setMark(Double mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.picPath
     *
     * @return the value of restaurant.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.picPath
     *
     * @param picpath the value for restaurant.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.picPath2
     *
     * @return the value of restaurant.picPath2
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getPicpath2() {
        return picpath2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.picPath2
     *
     * @param picpath2 the value for restaurant.picPath2
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPicpath2(String picpath2) {
        this.picpath2 = picpath2 == null ? null : picpath2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.reviews
     *
     * @return the value of restaurant.reviews
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getReviews() {
        return reviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.reviews
     *
     * @param reviews the value for restaurant.reviews
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setReviews(Integer reviews) {
        this.reviews = reviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.city
     *
     * @return the value of restaurant.city
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.city
     *
     * @param city the value for restaurant.city
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    @Override
    public String toString() {
        return "Restaurant{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", restaurantdescribe='" + restaurantdescribe + '\'' +
                ", price=" + price +
                ", mark=" + mark +
                ", picpath='" + picpath + '\'' +
                ", picpath2='" + picpath2 + '\'' +
                ", reviews=" + reviews +
                ", city='" + city + '\'' +
                '}';
    }
}