package cn.kgc.entity;

public class RestaurantOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantorder.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantorder.rid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantorder.uid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantorder.adult
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer adult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantorder.child
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer child;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantorder.comeDate
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String comedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantorder.times
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String times;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantorder.id
     *
     * @return the value of restaurantorder.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantorder.id
     *
     * @param id the value for restaurantorder.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantorder.rid
     *
     * @return the value of restaurantorder.rid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantorder.rid
     *
     * @param rid the value for restaurantorder.rid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantorder.uid
     *
     * @return the value of restaurantorder.uid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantorder.uid
     *
     * @param uid the value for restaurantorder.uid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantorder.adult
     *
     * @return the value of restaurantorder.adult
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getAdult() {
        return adult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantorder.adult
     *
     * @param adult the value for restaurantorder.adult
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setAdult(Integer adult) {
        this.adult = adult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantorder.child
     *
     * @return the value of restaurantorder.child
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getChild() {
        return child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantorder.child
     *
     * @param child the value for restaurantorder.child
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setChild(Integer child) {
        this.child = child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantorder.comeDate
     *
     * @return the value of restaurantorder.comeDate
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getComedate() {
        return comedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantorder.comeDate
     *
     * @param comedate the value for restaurantorder.comeDate
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setComedate(String comedate) {
        this.comedate = comedate == null ? null : comedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantorder.times
     *
     * @return the value of restaurantorder.times
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantorder.times
     *
     * @param times the value for restaurantorder.times
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setTimes(String times) {
        this.times = times == null ? null : times.trim();
    }
}