package cn.kgc.entity;

public class RoomType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.hid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.describe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String picpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.id
     *
     * @return the value of roomtype.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.id
     *
     * @param id the value for roomtype.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.hid
     *
     * @return the value of roomtype.hid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.hid
     *
     * @param hid the value for roomtype.hid
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.name
     *
     * @return the value of roomtype.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.name
     *
     * @param name the value for roomtype.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.describe
     *
     * @return the value of roomtype.describe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.describe
     *
     * @param describe the value for roomtype.describe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.picPath
     *
     * @return the value of roomtype.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.picPath
     *
     * @param picpath the value for roomtype.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }
}