package cn.kgc.entity;

public class Tour {

    @Override
    public String toString() {
        return "Tour{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", tourdescribe='" + tourdescribe + '\'' +
                ", price=" + price +
                ", mark=" + mark +
                ", picpath='" + picpath + '\'' +
                ", picpath2='" + picpath2 + '\'' +
                ", reviews=" + reviews +
                ", city='" + city + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourDescribe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String tourdescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.price
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Double mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String picpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.picPath2
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String picpath2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.reviews
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private Integer reviews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.city
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.id
     *
     * @return the value of tour.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.id
     *
     * @param id the value for tour.id
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.name
     *
     * @return the value of tour.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.name
     *
     * @param name the value for tour.name
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourDescribe
     *
     * @return the value of tour.tourDescribe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getTourdescribe() {
        return tourdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourDescribe
     *
     * @param tourdescribe the value for tour.tourDescribe
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setTourdescribe(String tourdescribe) {
        this.tourdescribe = tourdescribe == null ? null : tourdescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.price
     *
     * @return the value of tour.price
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.price
     *
     * @param price the value for tour.price
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.mark
     *
     * @return the value of tour.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Double getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.mark
     *
     * @param mark the value for tour.mark
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setMark(Double mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.picPath
     *
     * @return the value of tour.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.picPath
     *
     * @param picpath the value for tour.picPath
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.picPath2
     *
     * @return the value of tour.picPath2
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getPicpath2() {
        return picpath2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.picPath2
     *
     * @param picpath2 the value for tour.picPath2
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setPicpath2(String picpath2) {
        this.picpath2 = picpath2 == null ? null : picpath2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.reviews
     *
     * @return the value of tour.reviews
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public Integer getReviews() {
        return reviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.reviews
     *
     * @param reviews the value for tour.reviews
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setReviews(Integer reviews) {
        this.reviews = reviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.city
     *
     * @return the value of tour.city
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.city
     *
     * @param city the value for tour.city
     *
     * @mbg.generated Fri Aug 07 22:45:15 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}