package cn.kgc.entity;

import java.io.Serializable;

public class User implements Serializable{



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user11.id
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user11.age
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user11.userName
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user11.passWord
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user11.type
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user11.picPath
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    private String picpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user11.vip
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    private Integer vip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user11.vipDays
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    private Integer vipdays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user11.vipFreeTimes
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    private Integer vipfreetimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user11.id
     *
     * @return the value of user11.id
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user11.id
     *
     * @param id the value for user11.id
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user11.age
     *
     * @return the value of user11.age
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user11.age
     *
     * @param age the value for user11.age
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user11.userName
     *
     * @return the value of user11.userName
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user11.userName
     *
     * @param username the value for user11.userName
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user11.passWord
     *
     * @return the value of user11.passWord
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user11.passWord
     *
     * @param password the value for user11.passWord
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user11.type
     *
     * @return the value of user11.type
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user11.type
     *
     * @param type the value for user11.type
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user11.picPath
     *
     * @return the value of user11.picPath
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user11.picPath
     *
     * @param picpath the value for user11.picPath
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user11.vip
     *
     * @return the value of user11.vip
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public Integer getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user11.vip
     *
     * @param vip the value for user11.vip
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public void setVip(Integer vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user11.vipDays
     *
     * @return the value of user11.vipDays
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public Integer getVipdays() {
        return vipdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user11.vipDays
     *
     * @param vipdays the value for user11.vipDays
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public void setVipdays(Integer vipdays) {
        this.vipdays = vipdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user11.vipFreeTimes
     *
     * @return the value of user11.vipFreeTimes
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public Integer getVipfreetimes() {
        return vipfreetimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user11.vipFreeTimes
     *
     * @param vipfreetimes the value for user11.vipFreeTimes
     *
     * @mbg.generated Fri Aug 07 22:42:00 CST 2020
     */
    public void setVipfreetimes(Integer vipfreetimes) {
        this.vipfreetimes = vipfreetimes;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", age=" + age +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", type=" + type +
                ", picpath='" + picpath + '\'' +
                ", vip=" + vip +
                ", vipdays=" + vipdays +
                ", vipfreetimes=" + vipfreetimes +
                '}';
    }
}